version: "3.9"
services:
  myauction-db:
    image: postgres
    restart: always
    container_name: myauction-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
